### ISSUE TITLE
Sidebar location on a product's page

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/transcend-lite#1]
On a product's page the sidebar is shown at the bottom of the page, instead of on the right.
http://purealchemy.org.za/wp/product/life-is-good-organic-hemp-oil-orange-blossom/
https://gyazo.com/7287637a4dd665af083084c1ba3e2c4b

**Comment by giucu91** [comment]
This happens due to Ni WooCommerce Product Enquiry (https://wordpress.org/plugins/ni-woocommerce-product-enquiry/).
